# Site settings
title: Bucardo

# Build settings
markdown: kramdown

baseurl: ""

defaults:
    -
        scope:
            path: "" # Everything
        values:
            layout: "default"

gems:
    - jekyll-redirect-from
