# Site settings
title: Bucardo

# Build settings
markdown: kramdown

baseurl: "/bucardotest"

defaults:
    -
        scope:
            path: "" # Everything
        values:
            layout: "default"
